/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amd_aparapi_OpenCLRunner_MappedMethod */

#ifndef _Included_com_amd_aparapi_OpenCLRunner_MappedMethod
#define _Included_com_amd_aparapi_OpenCLRunner_MappedMethod
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
