/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amd_aparapi_OpenCLJNI */

#ifndef _Included_com_amd_aparapi_OpenCLJNI
#define _Included_com_amd_aparapi_OpenCLJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_amd_aparapi_OpenCLJNI
 * Method:    getPlatforms
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_amd_aparapi_OpenCLJNI_getPlatforms
  (JNIEnv *, jobject);

/*
 * Class:     com_amd_aparapi_OpenCLJNI
 * Method:    createProgram
 * Signature: (Lcom/amd/aparapi/OpenCLDevice;Ljava/lang/String;)Lcom/amd/aparapi/OpenCLProgram;
 */
JNIEXPORT jobject JNICALL Java_com_amd_aparapi_OpenCLJNI_createProgram
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_amd_aparapi_OpenCLJNI
 * Method:    createKernel
 * Signature: (Lcom/amd/aparapi/OpenCLProgram;Ljava/lang/String;Ljava/util/List;)Lcom/amd/aparapi/OpenCLKernel;
 */
JNIEXPORT jobject JNICALL Java_com_amd_aparapi_OpenCLJNI_createKernel
  (JNIEnv *, jobject, jobject, jstring, jobject);

/*
 * Class:     com_amd_aparapi_OpenCLJNI
 * Method:    invoke
 * Signature: (Lcom/amd/aparapi/OpenCLKernel;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_amd_aparapi_OpenCLJNI_invoke
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_amd_aparapi_OpenCLJNI
 * Method:    remap
 * Signature: (Lcom/amd/aparapi/OpenCLProgram;Lcom/amd/aparapi/OpenCLMem;J)V
 */
JNIEXPORT void JNICALL Java_com_amd_aparapi_OpenCLJNI_remap
  (JNIEnv *, jobject, jobject, jobject, jlong);

/*
 * Class:     com_amd_aparapi_OpenCLJNI
 * Method:    getMem
 * Signature: (Lcom/amd/aparapi/OpenCLProgram;Lcom/amd/aparapi/OpenCLMem;)V
 */
JNIEXPORT void JNICALL Java_com_amd_aparapi_OpenCLJNI_getMem
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_amd_aparapi_OpenCLJNI
 * Method:    getBytes
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_amd_aparapi_OpenCLJNI_getBytes
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
